data_dir: '/usr0/home/gis/data/tacred/data/json'
vocab_dir: '/usr0/home/gis/data/tacred/data/vocab'
test_save_dir: '/usr0/home/gis/research/tacred-exploration/tacred_test_performances'
save_dir: '/usr0/home/gis/research/tacred-exploration/saved_models'
emb_dim: 300  # Word embedding dimension.
ner_dim: 30 # NER embedding dimension.
pos_dim: 30 # POS embedding dimension.
hidden_dim: 300 # RNN hidden state size.
num_layers: 2 # Num of RNN layers.
input_dropout: .5 # Input and RNN dropout rate.
gcn_dropout: .5
word_dropout: .04 # The rate at which randomly set a word to UNK.
topn: 1e10  # Only finetune top N embeddings.
lower: False  # Lowercase all words.
heads: 3
sublayer_first: 2
sublayer_second: 4
pooling: 'max' # ['max', 'avg', 'sum']
pooling_l2: 0.002
mlp_layers: 1
no_adj: False
rnn: True
rnn_hidden: 300
rnn_layers: 1
rnn_dropout: 0.5
lr: 0.7 # Applies to SGD and Adagrad
lr_decay: 0.9
decay_epoch: 5
optim: 'sgd'  # sgd, adagrad, adam or adamax.
num_epoch: 100 # number of epochs
batch_size: 50
max_grad_norm: 5.0  # Gradient Clipping.
log_step: 20  # Print log every k steps.
log:  'logs.txt'  # Write training log to file.
save_epoch: 5 # Save model checkpoints every k epochs
id: 'AGGCN-TEST'  # Model ID under which to save models.
info: ''  # Optional info for the experiment.
seed: 37  # random seed
cuda: True
cpu: False # Ignore CUDA.
load: False
model_file:
link_prediction:
  model: 'ConvE'
  label_smoothing: .1
  lambda: 1.
  freeze_embeddings: False
  with_relu: True
